### ISSUE TITLE
Suggestion: change link color 

### ISSUE THREAD

**Issue by bnthurre0** [bnthurre/github-crash-couse#1]
i think it looks better if link  be a little more orange.

the styling rules changed be like this:

```css
 a {
    color: #e29d13;
  }

```
